### ISSUE TITLE
Support json based templates

### ISSUE THREAD

**Issue by mridhul** [intuit/cfn-deploy#11]
The current version supports only yaml based templates. Weneed to support json templates as well.

Ideal to to have a ENV variable which determines what type of file you are passing.
The default can be YAML

**Comment by codeR49** [comment]
i want to have a shot on this @mridhul

**Comment by mridhul** [comment]
@codeR49 sure. Are you clear on the requirement ? 

What we need is a feature on the cfn-deploy which supports the cloudformation deployment for json templates.

happy to have a quick call with you if you need more details

**Comment by mridhul** [comment]
Already supported Verified by DinkuSarmah (https://github.com/DinkuSarmah)
