### ISSUE TITLE
Timeout for stack creation

### ISSUE THREAD

**Issue by mridhul** [intuit/cfn-deploy#13]
The timeout value for the stack create/update should be cutomizable.
This should be a non mandatory parameter

**Comment by ambikaiyer29** [comment]
Hi @mridhul  - Please review this PR - https://github.com/intuit/cfn-deploy/pull/18

**Comment by ambikaiyer29** [comment]
Hi @mridhul  - any updates on this?

**Comment by mridhul** [comment]
@codemii . this is closed
