### ISSUE TITLE
configuring tzdata issue

### ISSUE THREAD

**Issue by mumar-FA** [intuit/cfn-deploy#23]
The installation is stuck on configuring tzdata and asking for user input to select region.
![tzdata](https://user-images.githubusercontent.com/73631763/98548928-f3d54080-22bb-11eb-9d8c-ca82bb1b18ce.PNG)

**Comment by samik-saha** [comment]
This may have been fixed already in PR #8 . Just need to create a new release version with the latest code?

**Comment by mridhul** [comment]
@samik-saha Closing this. thanks for your contribution, please do check the issues page and please contribute again. Please dont forget to add a star for the project :)
