### ISSUE TITLE
Create a readme on how to test the github actions

### ISSUE THREAD

**Issue by mridhul** [intuit/cfn-deploy#32]
Need a small write up and a short video on how to test the github actions while development

**Comment by shobha07** [comment]
> Need a small write up and a short video on how to test the github actions while development

@mridhul can you assign this to me pls.

**Comment by mridhul** [comment]
Done @shobha07 . Let me know if you want to catch up quickly

**Comment by anjaliguptaz** [comment]
@mridhul Is this still open to contribute ?

**Comment by shobha07** [comment]
@mridhul pull request #41

**Comment by mridhul** [comment]
@shobha07  
Closing this. thanks for your contribution, please do check the issues page and please contribute again. Please dont forget to add a star for the project :)
