### ISSUE TITLE
Add hacktoberfest topic to the repository

### ISSUE THREAD

**Issue by rylim** [intuit/cfn-deploy#33]
The `hacktoberfest` github topic <https://github.com/topics/hacktoberfest> should be added to the repository so it can officially participate in [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 🙂

<https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository>

**Comment by mridhul** [comment]
Thanks a lot @rylim . 
Done. 
Could you please verify that I have done it correctly ?

**Comment by rylim** [comment]
No problem @mridhul! I see the topic being added but it looks like there's a bit of a typo 🙂 (`hactoberfest` instead of `hacktoberfest` with a missing "k").

<img width="310" alt="image" src="https://user-images.githubusercontent.com/36293596/136889000-567da209-28ac-48c3-8e8d-ebd7d0649050.png">

**Comment by rylim** [comment]
You can see it as well by looking at the right sidebar of the repo <https://github.com/intuit/cfn-deploy> and clicking on one of the topics listed under "About", the `hacktoberfest` topic should bring you to <https://github.com/topics/hacktoberfest>.

**Comment by rylim** [comment]
I see that its been fixed now, awesome! 👍🏼 

<img width="310" alt="image" src="https://user-images.githubusercontent.com/36293596/136889870-ef41e85b-a036-4847-9e8e-28bd56bb2284.png">

**Comment by rylim** [comment]
Please feel free to close this issue or I can close it as well.
